@MRS = http://localhost:5099

GET {{MovieRentalSystem_HostAddress}}/weatherforecast/
Accept: application/json

###
//users api

GET {{MRS}}/api/users
Accept: application/json

###

GET {{MRS}}/api/users/1
Accept: application/json

###

PUT {{MRS}}/api/users/3
content-type: application/json
{
  "id": 1,
  "firstname": "ana",
  "lastname": "ali",
  "email": "ana@gmai.com",
  "password": "ana123",
  "roleId": "1"
}

###

POST {{MRS}}/api/users
content-type: application/json
{
  "firstname": "ali",
  "lastname": "asif",
  "email": "aasif@gmail.com",
  "password": "a123",
  "roleId": "1"

}







###
//roles api

GET {{MRS}}/api/roles
Accept: application/json

###

GET {{MRS}}/api/roles/2
Accept: application/json

###

PUT {{MRS}}/api/roles/2
content-type: application/json
{
  "id": 2,
  "roleName": "staff"
}

###

POST {{MRS}}/api/roles
content-type: application/json
{
  "roleName": "employees"
}









###
//movie status api

GET {{MRS}}/api/moviestatus
Accept: application/json

###

GET {{MRS}}/api/moviestatus/2
Accept: application/json

###

PUT {{MRS}}/api/moviestatus/1
Content-Type: application/json
{
  "id": 1,
  "statusName": "unavailable"
}

###

POST {{MRS}}/api/moviestatus
content-type: application/json
{
  "statusName": "discontinued"
}









###
//Movies api

GET {{MRS}}/api/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ1cm9vYmFAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiMSIsImV4cCI6MTc4NjQ0NTU3NywiaXNzIjoiTW92aWVSZW50YWxTeXN0ZW0iLCJhdWQiOiJNb3ZpZVJlbnRhbFN5c3RlbSJ9.EMZ48k6CKIfe7G9lYGi8Xu3A9N3gRzjFksKhaks2lIg

###

GET {{MRS}}/api/movies/1
Accept: application/json

###

PUT {{MRS}}/api/movies/1
content-type: application/json
{
  "id": 1,
  "movieTitle": "The Dark Knight",
  "director": "Christopher Nolan",
  "movieGenreId": 1,
  "movieStatusId": 1,
  "releaseYear": 2008,
  "rentalPrice": 3.99
}

### 

POST {{MRS}}/api/movies
content-type: application/json
{
  "movieTitle": "Inception",
  "director": "Christopher Nolan",
  "movieGenreId": 1,
  "movieStatusId": 1,
  "releaseYear": 2010,
  "rentalPrice": 4.99
}










###
///movie genres api

GET {{MRS}}/api/movieGenre
accept: application/json

###

GET {{MRS}}/api/movieGenre/1
Accept: application/json

###

PUT {{MRS}}/api/movieGenre/1
content-type: application/json
{
  "id" : 1,
  "movieGenre": "mystery"
}

###

POST {{MRS}}/api/movieGenre
content-type: application/json
{
  "movieGenre": "comedy"
}










###
//customer status api

GET {{MRS}}/api/customerStatus
Accept: application/json

###

GET {{MRS}}/api/customerStatus/1
Accept: application/json

###

PUT {{MRS}}/api/customerStatus/1
content-type: application/json
{
  "id": 1,
  "statusName": "inactive"
}

###

POST {{MRS}}/api/customerStatus
content-type: application/json
{
  "statusName": "suspended"
}










###
///customer api

GET {{MRS}}/api/customers
Accept: application/json

###

GET {{MRS}}/api/customers/1
Accept: application/json

###

PUT {{MRS}}/api/customers/1
content-type: application/json
{
  "id": 1,
  "firstname": "abeer",
  "lastname": "arif",
  "email": "abeer@gmail.com",
  "age": 21,
  "address": "islamabad",
  "customerStatusId": 1
}

###

POST {{MRS}}/api/customers
content-type: application/json
{
  "firstname": "sara",
  "lastname": "khan",
  "email": "sara@gmail.com",
  "age": 31,
  "address": "karachi",
  "customerStatusId": 2
}











###
//booking status api

GET {{MRS}}/api/bookingStatus
Accept: application/json

###

GET {{MRS}}/api/bookingStatus/1
acpt: application/json

###

PUT {{MRS}}/api/bookingStatus/1
content-type: application/json
{
  "id": 1,
  "statusName": "cancelled"
}

###

POST {{MRS}}/api/bookingStatus
Content-Type: application/json
{
  "statusName": "pending"
}









###
//booking api

GET {{MRS}}/api/bookings
Accept: application/json

###

GET {{MRS}}/api/bookings/1
Accept: application/json

###

PUT {{MRS}}/api/bookings/1
content-type: application/json
{
  "id": 1,
  "bookingDate": "2024-06-01T00:00:00",
  "returnDate": "2024-11-07T00:00:00",
  "totalPrice": 0,
    "totalDays": 0,
    "userId": 2,
    "movieId": 3,
    "customerId": 2,
    "bookingStatusId": 2
}

###

POST {{MRS}}/api/bookings
content-type: application/json
{
  "bookingDate": "2026-06-01T00:00:00",
  "returnDate": "2027-11-07T00:00:00",
  "totalPrice": 0,
    "totalDays": 0,
    "userId": 4,
    "movieId": 3,
    "customerId": 5,
    "bookingStatusId": 3
}








###
//authentication

POST {{MRS}}/api/auth/login
content-type: application/json
{
  "email": "urooba@gmail.com",
  "password": "admin123"
}

###

POST {{MRS}}/api/auth/login
content-type: application/json
{
  "email": "ayesha@gmail.com",
  "password": "employee567"
}

###

POST {{MRS}}/api/auth/login
content-type: application/json
{
  "email": "omer@gmail.com",
  "password": "employee567"
}
