@MRS = http://localhost:5099

GET {{MovieRentalSystem_HostAddress}}/weatherforecast/
Accept: application/json

###
//users api

GET {{MRS}}/api/users
Accept: application/json

###

GET {{MRS}}/api/users/1
Accept: application/json

###

PUT {{MRS}}/api/users/3
content-type: application/json
{
  "id": 1,
  "firstname": "ana",
  "lastname": "ali",
  "email": "ana@gmai.com",
  "password": "ana123",
  "roleId": "1"
}

###

POST {{MRS}}/api/users
content-type: application/json
{
  "firstname": "anaya",
  "lastname": "asif",
  "email": "anaya@gmail.com",
  "password": "anaya123",
  "roleId": "1"
}


###
//movie status api

GET {{MRS}}/api/moviestatus
Accept: application/json

###

GET {{MRS}}/api/moviestatus/2
Accept: application/json

###

PUT {{MRS}}/api/moviestatus/1
Content-Type: application/json
{
  "id": 1,
  "statusName": "unavailable"
}

###

POST {{MRS}}/api/moviestatus
content-type: application/json
{
  "statusName": "discontinued"
}


###
//customer status api

GET {{MRS}}/api/customerStatus
Accept: application/json

###

GET {{MRS}}/api/customerStatus/1
Accept: application/json

###

PUT {{MRS}}/api/customerStatus/1
content-type: application/json
{
  "id": 1,
  "statusName": "inactive"
}

###

POST {{MRS}}/api/customerStatus
content-type: application/json
{
  "statusName": "suspended"
}


###
//booking status api

GET {{MRS}}/api/bookingStatus
Accept: application/json

###

GET {{MRS}}/api/bookingStatus/1
acpt: application/json

###

PUT {{MRS}}/api/bookingStatus/1
content-type: application/json
{
  "id": 1,
  "statusName": "cancelled"
}

###

POST {{MRS}}/api/bookingStatus
Content-Type: application/json
{
  "statusName": "pending"
}

###
///movie genres api

GET {{MRS}}/api/movieGenre
accept: application/json

###

GET {{MRS}}/api/movieGenre/1
Accept: application/json

###

PUT {{MRS}}/api/movieGenre/1
content-type: application/json
{
  "id" : 1,
  "movieGenre": "mystery"
}

###

POST {{MRS}}/api/movieGenre
content-type: application/json
{
  "movieGenre": "comedy"
}