// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieRentalSystem.Data;

#nullable disable

namespace MovieRentalSystem.Migrations
{
    [DbContext(typeof(MovieRentalSystemContext))]
    [Migration("20260806185658_initial migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieRentalSystem.Models.BookingStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BookingStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StatusName = "Payment Pending"
                        },
                        new
                        {
                            Id = 2,
                            StatusName = "Payement Confirmed"
                        },
                        new
                        {
                            Id = 3,
                            StatusName = "Booking Cancelled"
                        },
                        new
                        {
                            Id = 4,
                            StatusName = "Completed"
                        });
                });

            modelBuilder.Entity("MovieRentalSystem.Models.Bookings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookingStatusId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingDate = new DateTime(2026, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingStatusId = 2,
                            CustomerId = 1,
                            MovieId = 1,
                            ReturnDate = new DateTime(2026, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalDays = 0,
                            TotalPrice = 0.0,
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            BookingDate = new DateTime(2026, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingStatusId = 1,
                            CustomerId = 2,
                            MovieId = 2,
                            ReturnDate = new DateTime(2026, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalDays = 0,
                            TotalPrice = 0.0,
                            UserId = 0
                        },
                        new
                        {
                            Id = 3,
                            BookingDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingStatusId = 4,
                            CustomerId = 3,
                            MovieId = 3,
                            ReturnDate = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalDays = 0,
                            TotalPrice = 0.0,
                            UserId = 0
                        },
                        new
                        {
                            Id = 4,
                            BookingDate = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingStatusId = 3,
                            CustomerId = 4,
                            MovieId = 4,
                            ReturnDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalDays = 0,
                            TotalPrice = 0.0,
                            UserId = 0
                        },
                        new
                        {
                            Id = 5,
                            BookingDate = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingStatusId = 2,
                            CustomerId = 5,
                            MovieId = 5,
                            ReturnDate = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalDays = 0,
                            TotalPrice = 0.0,
                            UserId = 0
                        },
                        new
                        {
                            Id = 6,
                            BookingDate = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingStatusId = 1,
                            CustomerId = 1,
                            MovieId = 6,
                            ReturnDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalDays = 0,
                            TotalPrice = 0.0,
                            UserId = 0
                        },
                        new
                        {
                            Id = 7,
                            BookingDate = new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingStatusId = 4,
                            CustomerId = 2,
                            MovieId = 1,
                            ReturnDate = new DateTime(2026, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalDays = 0,
                            TotalPrice = 0.0,
                            UserId = 0
                        },
                        new
                        {
                            Id = 8,
                            BookingDate = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingStatusId = 3,
                            CustomerId = 3,
                            MovieId = 2,
                            ReturnDate = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalDays = 0,
                            TotalPrice = 0.0,
                            UserId = 0
                        });
                });

            modelBuilder.Entity("MovieRentalSystem.Models.CustomerStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomerStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StatusName = "Defaulter"
                        },
                        new
                        {
                            Id = 2,
                            StatusName = "Regular"
                        },
                        new
                        {
                            Id = 3,
                            StatusName = "VIP"
                        },
                        new
                        {
                            Id = 4,
                            StatusName = "Not Allowed"
                        });
                });

            modelBuilder.Entity("MovieRentalSystem.Models.Customers", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CustomerStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "karachi",
                            Age = 31,
                            CustomerStatusId = 2,
                            Email = "john@gmail.com",
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "lahore",
                            Age = 25,
                            CustomerStatusId = 3,
                            Email = "jane@gmail.com",
                            FirstName = "Jane",
                            LastName = "Smith"
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "islamabad",
                            Age = 28,
                            CustomerStatusId = 1,
                            Email = "ali@gmail.com",
                            FirstName = "Ali",
                            LastName = "yawar"
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "peshawar",
                            Age = 30,
                            CustomerStatusId = 4,
                            Email = "ayesha@gmail.com",
                            FirstName = "Ayesha",
                            LastName = "ali"
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "quetta",
                            Age = 27,
                            CustomerStatusId = 2,
                            Email = "ahmed@gmail.com",
                            FirstName = "Ahmed",
                            LastName = "khan"
                        });
                });

            modelBuilder.Entity("MovieRentalSystem.Models.MovieGenres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("movieGenre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MovieGenres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            movieGenre = "Action"
                        },
                        new
                        {
                            Id = 2,
                            movieGenre = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            movieGenre = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            movieGenre = "Horror"
                        },
                        new
                        {
                            Id = 5,
                            movieGenre = "Romance"
                        },
                        new
                        {
                            Id = 6,
                            movieGenre = "Sci-Fi"
                        },
                        new
                        {
                            Id = 7,
                            movieGenre = "Thriller"
                        });
                });

            modelBuilder.Entity("MovieRentalSystem.Models.MovieStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MovieStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StatusName = "Available"
                        },
                        new
                        {
                            Id = 2,
                            StatusName = "Rented"
                        },
                        new
                        {
                            Id = 3,
                            StatusName = "Reserved"
                        },
                        new
                        {
                            Id = 4,
                            StatusName = "Not Available"
                        });
                });

            modelBuilder.Entity("MovieRentalSystem.Models.Movies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieGenreId")
                        .HasColumnType("int");

                    b.Property<int>("MovieStatusId")
                        .HasColumnType("int");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<double>("RentalPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Christopher Nolan",
                            MovieGenreId = 6,
                            MovieStatusId = 1,
                            MovieTitle = "Inception",
                            ReleaseYear = 2010,
                            RentalPrice = 6590.0
                        },
                        new
                        {
                            Id = 2,
                            Director = "Christopher Nolan",
                            MovieGenreId = 1,
                            MovieStatusId = 2,
                            MovieTitle = "The Dark Knight",
                            ReleaseYear = 2008,
                            RentalPrice = 5990.0
                        },
                        new
                        {
                            Id = 3,
                            Director = "Quentin Tarantino",
                            MovieGenreId = 1,
                            MovieStatusId = 3,
                            MovieTitle = "Pulp Fiction",
                            ReleaseYear = 1994,
                            RentalPrice = 4990.0
                        },
                        new
                        {
                            Id = 4,
                            Director = "Frank Darabont",
                            MovieGenreId = 3,
                            MovieStatusId = 4,
                            MovieTitle = "The Shawshank Redemption",
                            ReleaseYear = 1994,
                            RentalPrice = 3990.0
                        },
                        new
                        {
                            Id = 5,
                            Director = "Francis Ford Coppola",
                            MovieGenreId = 3,
                            MovieStatusId = 1,
                            MovieTitle = "The Godfather",
                            ReleaseYear = 1972,
                            RentalPrice = 6990.0
                        },
                        new
                        {
                            Id = 6,
                            Director = "Lana Wachowski, Lilly Wachowski",
                            MovieGenreId = 6,
                            MovieStatusId = 2,
                            MovieTitle = "The Matrix",
                            ReleaseYear = 1999,
                            RentalPrice = 5990.0
                        });
                });

            modelBuilder.Entity("MovieRentalSystem.Models.Roles", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Employee"
                        });
                });

            modelBuilder.Entity("MovieRentalSystem.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "urooba@gmail.com",
                            FirstName = "urooba",
                            LastName = "batool",
                            Password = "admin123",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            Email = "jia@gmail.com",
                            FirstName = "jia",
                            LastName = "batool",
                            Password = "employee123",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            Email = "ali@gmail.com",
                            FirstName = "Ali",
                            LastName = "Khan",
                            Password = "employee345",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            Email = "ayesha@gmail.com",
                            FirstName = "Ayesha",
                            LastName = "Khan",
                            Password = "employee567",
                            RoleId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
